export const tabs = [
  'Overview',
  'Expert Q&A',
  'News',
  'Innovative Use Cases',
  'Ecosystem',
  'Divider',
  'Recap',
  'Evolution',
  'Future roadmap',
  'Divider',
  'Funding and Investment',
  'Career Paths',
  'Skill Development',
  'Community and Events',
  'Divider',
  'Tech Stack',
  'Tech Deep Dive',
  'AI Tools and Platforms',
  'Divider',
  'Research',
  'Expert opinions',
  'Policy and Regulation',
  'Ethics',
  'Challenges and Solutions',
  'Global Perspectives',
  'Divider',
  'Comparisons',
  'Applications',
  'Case Studies',
  'Impact',
];

export const shouldWebSearch = {
  News: true,
  'Community and Events': true,
};
