export const tabs = [
  'Overview',
  'Expert Q&A',
  'News',
  'Recap',
  'Evolution',
  'Future roadmap',
  'Divider',
  'Ecosystem',
  'Funding and Investment',
  'Career Paths',
  'Skill Development',
  'Community and Events',
  'Divider',
  'Tech Stack',
  'Tech Deep Dive',
  'AI Tools and Platforms',
  'Divider',
  'Expert opinions',
  'Policy and Regulation',
  'Ethics',
  'Challenges and Solutions',
  'Global Perspectives',
  'Divider',
  'Comparisons',
  'Applications',
  'Case Studies',
  'Innovative Use Cases',
  'Impact',
];
