export const topics = {
  clusters: [
    {
      name: 'Core Machine Learning Concepts',
      topics: [
        'Deep Learning',
        'Natural Language Processing',
        'Computer Vision',
        'Speech Recognition',
        'Speech Synthesis',
        'Reinforcement Learning',
        'Generative Adversarial Networks (GANs)',
        'Transformers in NLP',
        'Federated Learning',
        'Self-Supervised Learning',
        'Anomaly Detection',
        'Transfer Learning',
        'Multi-Task Learning',
        'Meta-Learning',
        'Sparse Data Learning',
        'AI Ethics and Fairness',
        'Explainable AI (XAI)',
        'Graph Neural Networks',
        'Zero-Shot Learning',
        'AI in Network Analysis',
        'Causal Inference in AI',
      ],
    },
    {
      name: 'Emerging AI Technologies',
      topics: [
        'Quantum Machine Learning',
        'AI in Edge Computing',
        'Neuromorphic Computing',
        'Augmented Reality and AI',
        'Blockchain and AI',
        'Evolutionary Algorithms',
        'Hybrid AI Models',
        'Language Models (e.g., GPT, BERT)',
        'Synthetic Data Generation',
        'AI for Internet of Things (IoT)',
        'AI and Virtual Reality',
        '3D Vision and Processing',
        'AI in Wearables',
        'AI in Digital Twins',
        'AI for 5G Networks',
      ],
    },
    {
      name: 'Industry Applications',
      topics: [
        'AI in Healthcare',
        'AI in Finance and Fintech',
        'AI for Climate Change',
        'AI in Autonomous Vehicles and Mobility',
        'AI in Robotics and Automation',
        'AI in Cybersecurity',
        'AI for Drug Discovery',
        'AI in Agriculture',
        'AI in Retail',
        'AI in Education',
        'AI in Employment',
        'AI in Legal',
        'AI in Content Creation',
        'AI in Manufacturing',
        'AI in Supply Chain Management',
        'AI for Smart Cities',
        'AI in Energy Sector',
        'AI in Accessibility',
        'AI in Real Estate',
        'AI for Customer Service',
        'AI in Marketing',
        'AI in Social Media Analysis',
        'AI in Human Resources',
        'AI for Event Prediction',
        'AI for Accommodation Services',
        'AI in Cryptocurrency and Blockchain',
      ],
    },
    {
      name: 'Ethical and Responsible AI',
      topics: [
        'Ethical AI and Fairness',
        'Bias Detection and Mitigation',
        'Privacy-preserving AI',
        'Sustainable AI',
        'AI Governance',
        'Responsible AI Design',
        'AI and Intellectual Property',
        'AI Transparency',
        'AI Accountability',
        'AI and Human Rights',
        'AI in Workforce Development',
        'Social Impacts of AI',
        'AI and Global Ethics',
        'AI in Social Justice',
        'AI for Inclusivity',
        'AI and Environmental Impact',
      ],
    },
    {
      name: 'AI-Powered User Interaction',
      topics: [
        'AI-powered Chatbots and Virtual Assistants',
        'AI-driven Recommendation Systems',
        'Explainable AI (XAI)',
        'Natural Language Generation',
        'Emotion AI',
        'Voice and Speech Recognition',
        'Conversational AI',
        'Human-AI Collaboration',
        'Personalized AI Interfaces',
        'AI in Gaming',
        'AI for Personal Assistants',
        'AI in User Experience Design',
        'AI for Interactive Entertainment',
        'Interactive Entertainment',
        'AI in Social Media',
        'AI for Personalized Learning',
        'AI in Virtual Events',
      ],
    },
    {
      name: 'Data Science and Analysis',
      topics: [
        'Big Data Analytics',
        'Predictive Analytics',
        'Data Visualization',
        'Data Mining',
        'Statistical Modeling',
        'Data Warehousing',
        'Data Governance',
        'Real-time Data Processing',
        'Data Integration',
        'Machine Learning Pipelines',
        'Data Security',
        'Data Quality Management',
        'Data Science Platforms',
        'Advanced Analytics Techniques',
        'Data Ethics',
        'Data Collaboration Tools',
      ],
    },
    {
      name: 'Content Creation and Management',
      topics: [
        'Generative Art',
        'Content Automation',
        'Digital Asset Management',
        'AI in Journalism',
        'AI in Music Creation',
        'AI in Video Production',
        'AI for SEO',
        'Content Personalization',
        'Interactive Media',
        'AI in Advertising',
        'AI in Content Curation',
        'AI for Digital Marketing',
        'AI in Publishing',
        'AI in Graphic Design',
        'AI in Content Moderation',
        'AI for Content Distribution',
        'AI in Podcast Production',
      ],
    },
    {
      name: 'Environmental and Societal Impact',
      topics: [
        'AI for Wildlife Conservation',
        'AI in Disaster Response',
        'AI for Water Resource Management',
        'AI in Renewable Energy',
        'AI for Sustainable Agriculture',
        'AI in Pollution Control',
        'AI for Urban Planning',
        'AI in Public Health',
        'AI for Social Good Initiatives',
        'AI and Ethics in Society',
        'AI for Energy Efficiency',
        'AI in Conservation Biology',
        'AI for Global Health',
      ],
    },
    {
      name: 'AI Research and Theory',
      topics: [
        'Theoretical Foundations of AI',
        'AI Model Interpretability',
        'AI Algorithm Efficiency',
        'AI in Cognitive Science',
        'Machine Learning Theory',
        'AI Model Generalization',
        'AI Safety and Security',
        'AI Model Robustness',
        'AI in Quantum Computing',
        'AI in Complex Systems',
        'AI and Neuroscience',
        'AI in Simulation and Modeling',
        'AI Ethics Research',
      ],
    },
    {
      name: 'AI Infrastructure and Platforms',
      topics: [
        'Cloud AI Services',
        'AI Hardware Accelerators',
        'AI Model Deployment',
        'AI Development Tools',
        'AI Model Monitoring',
        'AI in Edge Devices',
        'AI Data Lakes',
        'AI Model Management',
        'AI Scalability Solutions',
        'AI with Blockchain Integration',
        'AI Operations (AIOps)',
        'AI in DevOps',
        'AI for IT Automation',
      ],
    },
  ],
};
