export const topics = {
  clusters: [
    {
      name: 'Core Machine Learning Concepts',
      topics: [
        'Deep Learning',
        'Natural Language Processing',
        'Computer Vision',
        'Reinforcement Learning',
        'Generative Adversarial Networks (GANs)',
        'Transformers in NLP',
        'Federated Learning',
        'Self-Supervised Learning',
        'Anomaly Detection',
        'Transfer Learning',
        'Multi-Task Learning',
        'Meta-Learning',
        'Sparse Data Learning',
        'AI Ethics and Fairness',
        'Explainable AI (XAI)',
      ],
    },
    {
      name: 'Emerging AI Technologies',
      topics: [
        'Quantum Machine Learning',
        'AI in Edge Computing',
        'Neuromorphic Computing',
        'Augmented Reality and AI',
        'Blockchain and AI',
        'Evolutionary Algorithms',
        'Hybrid AI Models',
        'Language Models (e.g., GPT, BERT)',
        'Synthetic Data Generation',
        'AI for Internet of Things (IoT)',
      ],
    },
    {
      name: 'AI Applications in Industries',
      topics: [
        'AI in Healthcare',
        'AI in Finance and Fintech',
        'AI for Climate Change',
        'AI in Autonomous Vehicles and Mobility',
        'AI in Robotics and Automation',
        'AI in Cybersecurity',
        'AI for Drug Discovery',
        'AI in Agriculture',
        'AI in Retail',
        'AI in Education',
        'AI in Content Creation',
        'AI in Manufacturing',
        'AI in Supply Chain Management',
        'AI for Smart Cities',
        'AI in Energy Sector',
      ],
    },
    {
      name: 'Ethical and Responsible AI',
      topics: [
        'Ethical AI and Fairness',
        'Bias Detection and Mitigation',
        'Privacy-preserving AI',
        'Sustainable AI',
        'AI Governance',
        'Responsible AI Design',
        'AI and Intellectual Property',
        'AI Transparency',
        'AI Accountability',
        'AI and Human Rights',
      ],
    },
    {
      name: 'AI-Powered User Interaction',
      topics: [
        'AI-powered Chatbots and Virtual Assistants',
        'AI-driven Recommendation Systems',
        'Explainable AI (XAI)',
        'Natural Language Generation',
        'Emotion AI',
        'Voice and Speech Recognition',
        'Conversational AI',
        'Human-AI Collaboration',
        'Personalized AI Interfaces',
        'AI in Gaming',
      ],
    },
    {
      name: 'Data Science and Analysis',
      topics: [
        'Big Data Analytics',
        'Predictive Analytics',
        'Data Visualization',
        'Data Mining',
        'Statistical Modeling',
        'Data Warehousing',
        'Data Governance',
        'Real-time Data Processing',
        'Data Integration',
        'Machine Learning Pipelines',
      ],
    },
    {
      name: 'AI in Content Creation and Management',
      topics: [
        'Generative Art',
        'Content Automation',
        'Digital Asset Management',
        'AI in Journalism',
        'AI in Music Creation',
        'AI in Video Production',
        'AI for SEO',
        'Content Personalization',
        'Interactive Media',
        'AI in Advertising',
      ],
    },
    {
      name: 'AI for Environmental and Societal Impact',
      topics: [
        'AI for Wildlife Conservation',
        'AI in Disaster Response',
        'AI for Water Resource Management',
        'AI in Renewable Energy',
        'AI for Sustainable Agriculture',
        'AI in Pollution Control',
        'AI for Urban Planning',
        'AI in Public Health',
        'AI for Social Good Initiatives',
        'AI and Ethics in Society',
      ],
    },
    {
      name: 'AI Research and Theory',
      topics: [
        'Theoretical Foundations of AI',
        'AI Model Interpretability',
        'AI Algorithm Efficiency',
        'AI and Cognitive Science',
        'Machine Learning Theory',
        'AI Model Generalization',
        'AI Safety and Security',
        'AI Model Robustness',
        'AI and Quantum Computing',
        'AI in Complex Systems',
      ],
    },
    {
      name: 'AI Infrastructure and Platforms',
      topics: [
        'Cloud AI Services',
        'AI Hardware Accelerators',
        'AI Model Deployment',
        'AI Development Tools',
        'AI Model Monitoring',
        'AI in Edge Devices',
        'AI Data Lakes',
        'AI Model Management',
        'AI Scalability Solutions',
        'AI and Blockchain Integration',
      ],
    },
  ],
};
